import os
from datetime import datetime
from operator import itemgetter

DEF_DATE_FMT = "%m/%d/%Y"


def get_amount(row) -> float:
    amount_str = row.get("Valor(R$)", "").replace(",", ".").strip()
    return float(amount_str) * -1  ## positive values are debits in the CSV file


def is_credit(row) -> bool:
    if get_amount(row) > 0:
        return True

    return False


def parse_bradesco_date(date_str: str) -> datetime:
    """
    Parses a date string in the format 'DD/MM' and returns a datetime object.
    Uses the year from BRADESCO_CREDITCARD_YEAR env variable if set, otherwise current year.
    """
    try:
        day, month = map(int, date_str.strip().split("/"))
        year = int(os.getenv("BRADESCO_CREDITCARD_YEAR", datetime.now().year))
        return datetime(year=year, month=month, day=day)
    except (ValueError, TypeError) as e:
        raise ValueError(f"Invalid date format or values: '{date_str}'") from e


def bradesco_creditcard_filter(transaction) -> bool:
    # the csv file generated by them contains a lot of rows with other miscellaneous data that isn't relevant here
    try:
        parse_bradesco_date(transaction.get("Data"))
        return True
    except ValueError:
        return False


mapping = {
    "has_header": True,
    "first_row": 5,
    "filter": bradesco_creditcard_filter,
    "is_split": False,
    "bank": "Bradesco",
    "bank_id": "237",
    "currency": "R$",
    "delimiter": ";",
    "account": os.environ.get("BRADESCO_ACCOUNT", "1000002"),
    "date": lambda r: parse_bradesco_date(r.get("Data")).strftime(DEF_DATE_FMT),
    "parse_fmt": DEF_DATE_FMT,
    "date_fmt": DEF_DATE_FMT,
    "amount": lambda r: str(get_amount(r)),
    "desc": itemgetter("Histórico"),
    "type": lambda tr: "credit" if is_credit(tr) else "debit",
}
