import os
from datetime import datetime
from operator import itemgetter

DEF_DATE_FMT = "%d/%m/%Y"


def get_amount(row) -> float:
    amount_str = row.get("Valor(R$)", "").replace(",", ".").strip()
    return float(amount_str) * -1  ## positive values are debits in the CSV file


def is_credit(row) -> bool:
    if get_amount(row) > 0:
        return True

    return False


def parse_bradesco_date(date_str: str) -> datetime:
    """
    Parses a date string in the format 'DD/MM' and returns a datetime object.
    Uses the year from BRADESCO_CREDITCARD_YEAR env variable if set, otherwise current year.
    """
    try:
        day, month = map(int, date_str.strip().split("/"))
        year = int(os.getenv("BRADESCO_CREDITCARD_YEAR", datetime.now().year))
        return datetime(year=year, month=month, day=day)
    except (ValueError, TypeError) as e:
        raise ValueError(f"Invalid date format or values: '{date_str}'") from e


def bradesco_creditcard_filter(transaction) -> bool:
    # the csv file generated by them contains a lot of rows with other miscellaneous data that isn't relevant here
    try:
        parse_bradesco_date(transaction.get("Data"))
        return True
    except ValueError:
        return False


_previous_date = None
_dt_dict = {}


def get_date(row) -> str:
    global _previous_date
    global _dt_dict
    dt_str = row.get("Data")
    if _dt_dict.get(dt_str) is not None:
        return _dt_dict[dt_str]

    dt = parse_bradesco_date(dt_str)
    if _previous_date is not None and dt > _previous_date:
        # this is a workaround for the fact that the CSV file dates only have the day and month
        # however, since the transactions are ordered by date descending, we can assume that
        # if the parsed date is greater than the previous date, it means that this is a transaction from the previous year
        print(
            f"Patching {row.get('Histórico')} date from {dt.strftime(DEF_DATE_FMT)} year from {dt.year} to {dt.year - 1}"
        )
        dt = dt.replace(year=dt.year - 1)

    _previous_date = dt
    res = dt.strftime(DEF_DATE_FMT)
    _dt_dict[dt_str] = res
    return res


mapping = {
    "has_header": True,
    "first_row": 5,
    "filter": bradesco_creditcard_filter,
    "is_split": False,
    "bank": "Bradesco",
    "bank_id": "0237",
    "currency": "BRL",
    "delimiter": ";",
    "account": os.environ.get("BRADESCO_ACCOUNT", "1000002"),
    "date": get_date,
    "parse_fmt": DEF_DATE_FMT,
    "date_fmt": DEF_DATE_FMT,
    "amount": lambda r: str(get_amount(r)),
    "desc": itemgetter("Histórico"),
    "type": lambda tr: "credit" if is_credit(tr) else "debit",
}
